### ISSUE TITLE
Suggested enhancements for Control Center

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_control_center#4]
* Left nav takes up a lot of unused space. It could be more narrow, and/or appear as a fly-out menu when user interacts with it. 

* More hover text for all areas, especially column headers. This would allow us to shorten "Total Tests" to "Tests" and then use the hover text for a longer description.

**Comment by psilaghi** [comment]
Hi Matt!
I've made the navbar to be collapsible. Take a look and let me know what you think. The idea is important, the styling can be improved.

**Comment by mwobensmith** [comment]
Hi @psilaghi ! Looks fantastic! It's going in. I'll keep the issue open to track work on the second item above. Thank you!

**Comment by mwobensmith** [comment]
Excellent! I went ahead and merged it. Hope that is OK!

Thank you!

**Comment by mwobensmith** [comment]
Also, we'll keep the branch around and you can keep adding to it if you like. When we have more code to check in, I'll just merge the same branch.

**Comment by psilaghi** [comment]
Sounds perfect!

**Comment by psilaghi** [comment]
Hi Matt!
I improved the sidebar styling and also added some tooltips to the table headers and buttons.
Let me know if you have any suggestions.

**Comment by mwobensmith** [comment]
@psilaghi Hi Paul! I will look at this shortly, sorry, been busy!

**Comment by mwobensmith** [comment]
@psilaghi: Looks great, I'm merging it now and we can close this issue. Thank you! :D
